# Generated by Django 4.0.6 on 2022-07-25 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CR_USER_INFO',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_age', models.IntegerField()),
                ('user_sex', models.TextField()),
                ('user_disease', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CR_BIOFILE_INFO',
            fields=[
                ('file_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=200)),
                ('file_name', models.CharField(max_length=300)),
                ('file_rname', models.CharField(max_length=300)),
                ('file_ext', models.CharField(max_length=10)),
                ('file_size', models.CharField(max_length=30)),
                ('file_savetime', models.DateTimeField(auto_now_add=True)),
                ('file_user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='CR_USER_INFO', to='AIAPI.cr_user_info')),
            ],
        ),
    ]
