# Generated by Django 4.0.6 on 2022-07-25 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AIAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cr_biofile_info',
            name='file_user_id',
            field=models.ForeignKey(db_column='file_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='CR_USER_INFO', to='AIAPI.cr_user_info'),
        ),
    ]
